"""
FoxESS Solar Data — Visualization Dashboard
=============================================
Reads CSV data generated by fox_data_extract.py and creates
comprehensive charts for analyzing solar panel performance.

Usage:
    python fox_visualize.py

Input:
    - solar_report_6months.csv   (daily totals)
    - solar_history_6months.csv  (5-min interval data, optional)

Output:
    - output/ directory with high-res PNG charts
"""

import os
import sys
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')  # Non-interactive backend for saving files
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from matplotlib.gridspec import GridSpec
from datetime import datetime

# ── Paths ──
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPORT_CSV = os.path.join(SCRIPT_DIR, "solar_report_6months.csv")
HISTORY_CSV = os.path.join(SCRIPT_DIR, "solar_history_6months.csv")
OUTPUT_DIR = os.path.join(SCRIPT_DIR, "output")

# ── Style Configuration ──
COLORS = {
    'generation':    '#FFB800',  # Solar gold
    'feedin':        '#00C853',  # Green (export)
    'grid':          '#FF5252',  # Red (import)
    'charge':        '#448AFF',  # Blue (battery charge)
    'discharge':     '#FF6D00',  # Orange (battery discharge)
    'load':          '#7C4DFF',  # Purple (consumption)
    'pv_power':      '#FFC107',  # Amber
    'background':    '#1a1a2e',  # Dark navy
    'card':          '#16213e',  # Card background
    'text':          '#e0e0e0',  # Light text
    'accent':        '#0f3460',  # Accent blue
    'grid_line':     '#2a2a4a',  # Subtle grid
}

plt.rcParams.update({
    'figure.facecolor': COLORS['background'],
    'axes.facecolor': COLORS['card'],
    'axes.edgecolor': COLORS['grid_line'],
    'axes.labelcolor': COLORS['text'],
    'text.color': COLORS['text'],
    'xtick.color': COLORS['text'],
    'ytick.color': COLORS['text'],
    'grid.color': COLORS['grid_line'],
    'grid.alpha': 0.3,
    'font.family': 'sans-serif',
    'font.size': 11,
    'axes.titlesize': 14,
    'axes.titleweight': 'bold',
    'figure.titlesize': 18,
    'figure.titleweight': 'bold',
})


def load_report_data() -> pd.DataFrame:
    """Load and clean the daily report CSV."""
    if not os.path.exists(REPORT_CSV):
        print(f"  ✗ Report CSV not found: {REPORT_CSV}")
        print("    Run 'python fox_data_extract.py' first!")
        sys.exit(1)

    df = pd.read_csv(REPORT_CSV, parse_dates=['date'])
    df = df.sort_values('date').reset_index(drop=True)

    # Rename columns for clarity
    rename_map = {
        'generation': 'generation_kwh',
        'feedin': 'feedin_kwh',
        'gridConsumption': 'grid_consumption_kwh',
        'chargeEnergyToTal': 'battery_charge_kwh',
        'dischargeEnergyToTal': 'battery_discharge_kwh',
    }
    for old, new in rename_map.items():
        if old in df.columns:
            df.rename(columns={old: new}, inplace=True)

    # Fill NaN with 0
    numeric_cols = df.select_dtypes(include=[np.number]).columns
    df[numeric_cols] = df[numeric_cols].fillna(0)

    # Add derived columns
    if 'generation_kwh' in df.columns and 'grid_consumption_kwh' in df.columns:
        total_consumed = df['generation_kwh'] + df['grid_consumption_kwh']
        total_consumed = total_consumed.replace(0, np.nan)
        df['self_sufficiency_pct'] = (df['generation_kwh'] / total_consumed * 100).fillna(0)
        df['self_sufficiency_pct'] = df['self_sufficiency_pct'].clip(0, 100)

    df['day_of_week'] = df['date'].dt.day_name()
    df['week_number'] = df['date'].dt.isocalendar().week.astype(int)

    print(f"  ✓ Loaded report data: {len(df)} days")
    print(f"    Date range: {df['date'].min().strftime('%Y-%m-%d')} → {df['date'].max().strftime('%Y-%m-%d')}")
    return df


def load_history_data() -> pd.DataFrame:
    """Load the granular history CSV (optional)."""
    if not os.path.exists(HISTORY_CSV):
        print(f"  ⚠ History CSV not found (optional): {HISTORY_CSV}")
        return pd.DataFrame()

    df = pd.read_csv(HISTORY_CSV)

    # Try to parse timestamp
    if 'timestamp' in df.columns:
        df['timestamp'] = pd.to_datetime(df['timestamp'], errors='coerce')
        df = df.dropna(subset=['timestamp'])
        df = df.sort_values('timestamp').reset_index(drop=True)

    # Fill NaN with 0
    numeric_cols = df.select_dtypes(include=[np.number]).columns
    df[numeric_cols] = df[numeric_cols].fillna(0)

    print(f"  ✓ Loaded history data: {len(df)} records")
    return df


def chart_1_daily_generation(df: pd.DataFrame):
    """Bar chart of daily solar generation."""
    fig, ax = plt.subplots(figsize=(16, 6))

    dates = df['date']
    generation = df.get('generation_kwh', pd.Series(dtype=float)).fillna(0)

    # Color bars by intensity
    max_gen = generation.max() if generation.max() > 0 else 1
    colors = plt.cm.YlOrRd(generation / max_gen * 0.8 + 0.1)

    ax.bar(dates, generation, color=colors, width=0.8, edgecolor='none', alpha=0.9)

    # Add average line
    avg = generation.mean()
    ax.axhline(y=avg, color=COLORS['generation'], linestyle='--', linewidth=1.5, alpha=0.7,
               label=f'Average: {avg:.1f} kWh/day')

    ax.set_xlabel('Date')
    ax.set_ylabel('Generation (kWh)')
    ax.set_title('☀️  Daily Solar Generation — Last 6 Months')
    ax.legend(loc='upper right', facecolor=COLORS['card'], edgecolor=COLORS['grid_line'])
    ax.xaxis.set_major_formatter(mdates.DateFormatter('%b %d'))
    ax.xaxis.set_major_locator(mdates.WeekdayLocator(interval=2))
    plt.xticks(rotation=45, ha='right')
    ax.grid(axis='y', alpha=0.2)
    ax.set_xlim(dates.min() - pd.Timedelta(days=1), dates.max() + pd.Timedelta(days=1))

    plt.tight_layout()
    save_chart(fig, "01_daily_generation.png")


def chart_2_energy_flow(df: pd.DataFrame):
    """Stacked area chart showing energy flow breakdown."""
    fig, ax = plt.subplots(figsize=(16, 6))

    dates = df['date']
    generation = df.get('generation_kwh', pd.Series(0, index=df.index))
    feedin = df.get('feedin_kwh', pd.Series(0, index=df.index))
    grid = df.get('grid_consumption_kwh', pd.Series(0, index=df.index))

    ax.fill_between(dates, generation, alpha=0.6, color=COLORS['generation'], label='Generation')
    ax.fill_between(dates, feedin, alpha=0.5, color=COLORS['feedin'], label='Grid Export (Feed-in)')
    ax.fill_between(dates, -grid, alpha=0.5, color=COLORS['grid'], label='Grid Import')

    ax.axhline(y=0, color=COLORS['text'], linewidth=0.5, alpha=0.5)

    ax.set_xlabel('Date')
    ax.set_ylabel('Energy (kWh)')
    ax.set_title('⚡  Energy Flow — Generation vs Grid Exchange')
    ax.legend(loc='upper right', facecolor=COLORS['card'], edgecolor=COLORS['grid_line'])
    ax.xaxis.set_major_formatter(mdates.DateFormatter('%b %d'))
    ax.xaxis.set_major_locator(mdates.WeekdayLocator(interval=2))
    plt.xticks(rotation=45, ha='right')
    ax.grid(axis='y', alpha=0.2)

    plt.tight_layout()
    save_chart(fig, "02_energy_flow.png")


def chart_3_weekly_heatmap(df: pd.DataFrame):
    """Heatmap showing average generation by day of week."""
    fig, ax = plt.subplots(figsize=(10, 6))

    day_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
    generation_col = 'generation_kwh' if 'generation_kwh' in df.columns else df.columns[1]

    weekly = df.groupby('day_of_week')[generation_col].agg(['mean', 'max', 'min', 'count'])
    weekly = weekly.reindex(day_order)

    bars = ax.barh(range(len(day_order)), weekly['mean'], color=COLORS['generation'],
                   alpha=0.8, edgecolor='none', height=0.6)

    # Add value labels
    for i, (mean_val, max_val) in enumerate(zip(weekly['mean'], weekly['max'])):
        ax.text(mean_val + 0.1, i, f'{mean_val:.1f} kWh', va='center',
                fontsize=10, color=COLORS['text'])

    ax.set_yticks(range(len(day_order)))
    ax.set_yticklabels(day_order)
    ax.set_xlabel('Average Daily Generation (kWh)')
    ax.set_title('📅  Average Generation by Day of Week')
    ax.invert_yaxis()
    ax.grid(axis='x', alpha=0.2)

    plt.tight_layout()
    save_chart(fig, "03_weekly_pattern.png")


def chart_4_cumulative_generation(df: pd.DataFrame):
    """Cumulative energy generation over time."""
    fig, ax = plt.subplots(figsize=(16, 6))

    dates = df['date']
    generation = df.get('generation_kwh', pd.Series(0, index=df.index))
    cumulative = generation.cumsum()

    ax.fill_between(dates, cumulative, alpha=0.3, color=COLORS['generation'])
    ax.plot(dates, cumulative, color=COLORS['generation'], linewidth=2.5, label='Cumulative Generation')

    # Add total label
    total = cumulative.iloc[-1] if len(cumulative) > 0 else 0
    ax.text(dates.iloc[-1], total, f'  {total:.0f} kWh total',
            fontsize=12, fontweight='bold', color=COLORS['generation'], va='bottom')

    ax.set_xlabel('Date')
    ax.set_ylabel('Cumulative Energy (kWh)')
    ax.set_title('📈  Cumulative Solar Generation Over 6 Months')
    ax.legend(loc='upper left', facecolor=COLORS['card'], edgecolor=COLORS['grid_line'])
    ax.xaxis.set_major_formatter(mdates.DateFormatter('%b %d'))
    ax.xaxis.set_major_locator(mdates.WeekdayLocator(interval=2))
    plt.xticks(rotation=45, ha='right')
    ax.grid(axis='y', alpha=0.2)

    plt.tight_layout()
    save_chart(fig, "04_cumulative_generation.png")


def chart_5_self_sufficiency(df: pd.DataFrame):
    """Daily solar self-sufficiency ratio."""
    if 'self_sufficiency_pct' not in df.columns:
        print("  ⚠ Skipping self-sufficiency chart (no data)")
        return

    fig, ax = plt.subplots(figsize=(16, 6))

    dates = df['date']
    pct = df['self_sufficiency_pct']

    # Color based on sufficiency level
    colors = ['#FF5252' if p < 30 else '#FFB800' if p < 60 else '#00C853' for p in pct]

    ax.bar(dates, pct, color=colors, width=0.8, alpha=0.85, edgecolor='none')

    # Add average line
    avg = pct.mean()
    ax.axhline(y=avg, color='#448AFF', linestyle='--', linewidth=1.5,
               label=f'Average: {avg:.0f}%')

    ax.set_xlabel('Date')
    ax.set_ylabel('Self-Sufficiency (%)')
    ax.set_title('🏠  Daily Solar Self-Sufficiency Ratio')
    ax.set_ylim(0, 105)
    ax.legend(loc='upper right', facecolor=COLORS['card'], edgecolor=COLORS['grid_line'])
    ax.xaxis.set_major_formatter(mdates.DateFormatter('%b %d'))
    ax.xaxis.set_major_locator(mdates.WeekdayLocator(interval=2))
    plt.xticks(rotation=45, ha='right')
    ax.grid(axis='y', alpha=0.2)

    plt.tight_layout()
    save_chart(fig, "05_self_sufficiency.png")


def chart_6_box_plot_weekly(df: pd.DataFrame):
    """Box plot of daily generation grouped by week."""
    fig, ax = plt.subplots(figsize=(16, 6))

    generation_col = 'generation_kwh' if 'generation_kwh' in df.columns else df.columns[1]
    weeks = sorted(df['week_number'].unique())

    data_by_week = [df[df['week_number'] == w][generation_col].values for w in weeks]
    week_labels = [f'W{w}' for w in weeks]

    bp = ax.boxplot(data_by_week, labels=week_labels, patch_artist=True,
                    boxprops=dict(facecolor=COLORS['generation'], alpha=0.6),
                    medianprops=dict(color='white', linewidth=2),
                    whiskerprops=dict(color=COLORS['text']),
                    capprops=dict(color=COLORS['text']),
                    flierprops=dict(markerfacecolor=COLORS['grid'], markersize=4))

    ax.set_xlabel('Week Number')
    ax.set_ylabel('Daily Generation (kWh)')
    ax.set_title('📊  Generation Distribution by Week')
    ax.grid(axis='y', alpha=0.2)
    plt.xticks(rotation=45, ha='right')

    plt.tight_layout()
    save_chart(fig, "06_weekly_boxplot.png")


def chart_7_summary_dashboard(df: pd.DataFrame):
    """Summary statistics dashboard."""
    fig = plt.figure(figsize=(16, 10))
    fig.suptitle('🌞  Solar Panel Performance Dashboard — 6-Month Summary',
                 fontsize=20, fontweight='bold', y=0.98)

    gs = GridSpec(2, 3, figure=fig, hspace=0.4, wspace=0.3)

    generation = df.get('generation_kwh', pd.Series(0, index=df.index))
    feedin = df.get('feedin_kwh', pd.Series(0, index=df.index))
    grid = df.get('grid_consumption_kwh', pd.Series(0, index=df.index))

    # ── KPI Cards ──
    kpis = [
        ("Total Generated", f"{generation.sum():.0f} kWh", COLORS['generation']),
        ("Daily Average", f"{generation.mean():.1f} kWh", '#00C853'),
        ("Peak Day", f"{generation.max():.1f} kWh", '#FF6D00'),
        ("Grid Export", f"{feedin.sum():.0f} kWh", COLORS['feedin']),
        ("Grid Import", f"{grid.sum():.0f} kWh", COLORS['grid']),
        ("Best Day", df.loc[generation.idxmax(), 'date'].strftime('%b %d') if len(generation) > 0 and generation.max() > 0 else 'N/A', '#448AFF'),
    ]

    for i, (label, value, color) in enumerate(kpis):
        row, col = divmod(i, 3)
        ax = fig.add_subplot(gs[row, col])

        ax.text(0.5, 0.65, value, fontsize=28, fontweight='bold',
                color=color, ha='center', va='center', transform=ax.transAxes)
        ax.text(0.5, 0.25, label, fontsize=13,
                color=COLORS['text'], ha='center', va='center', transform=ax.transAxes,
                alpha=0.7)

        # Card styling
        ax.set_xlim(0, 1)
        ax.set_ylim(0, 1)
        ax.set_xticks([])
        ax.set_yticks([])
        for spine in ax.spines.values():
            spine.set_color(color)
            spine.set_linewidth(2)
            spine.set_alpha(0.4)

    plt.tight_layout(rect=[0, 0, 1, 0.95])
    save_chart(fig, "07_summary_dashboard.png")


def chart_8_history_power_profile(df_history: pd.DataFrame):
    """Power profile from granular history data (if available)."""
    if df_history.empty:
        print("  ⚠ Skipping power profile chart (no history data)")
        return

    if 'timestamp' not in df_history.columns:
        print("  ⚠ Skipping power profile chart (no timestamp column)")
        return

    fig, ax = plt.subplots(figsize=(16, 6))

    # Get the last available day with data
    df_history['hour'] = df_history['timestamp'].dt.hour + df_history['timestamp'].dt.minute / 60

    # Average power profile across all days
    pv_col = 'pvPower' if 'pvPower' in df_history.columns else None
    load_col = 'loadsPower' if 'loadsPower' in df_history.columns else None
    grid_col = 'gridConsumptionPower' if 'gridConsumptionPower' in df_history.columns else None
    feedin_col = 'feedinPower' if 'feedinPower' in df_history.columns else None

    # Bin by hour (rounded to nearest 5 min)
    df_history['hour_bin'] = (df_history['hour'] * 12).round() / 12  # 5-min bins

    if pv_col:
        hourly_pv = df_history.groupby('hour_bin')[pv_col].mean()
        ax.fill_between(hourly_pv.index, hourly_pv.values, alpha=0.4, color=COLORS['generation'])
        ax.plot(hourly_pv.index, hourly_pv.values, color=COLORS['generation'],
                linewidth=2, label='PV Power')

    if load_col:
        hourly_load = df_history.groupby('hour_bin')[load_col].mean()
        ax.plot(hourly_load.index, hourly_load.values, color=COLORS['load'],
                linewidth=2, label='Load', linestyle='--')

    if feedin_col:
        hourly_feedin = df_history.groupby('hour_bin')[feedin_col].mean()
        ax.plot(hourly_feedin.index, hourly_feedin.values, color=COLORS['feedin'],
                linewidth=1.5, label='Grid Export', alpha=0.7)

    if grid_col:
        hourly_grid = df_history.groupby('hour_bin')[grid_col].mean()
        ax.plot(hourly_grid.index, hourly_grid.values, color=COLORS['grid'],
                linewidth=1.5, label='Grid Import', alpha=0.7)

    ax.set_xlabel('Hour of Day')
    ax.set_ylabel('Average Power (kW)')
    ax.set_title('⏰  Average Daily Power Profile (All Days Combined)')
    ax.set_xlim(0, 24)
    ax.set_xticks(range(0, 25, 2))
    ax.set_xticklabels([f'{h:02d}:00' for h in range(0, 25, 2)])
    ax.legend(loc='upper right', facecolor=COLORS['card'], edgecolor=COLORS['grid_line'])
    ax.grid(alpha=0.2)

    plt.tight_layout()
    save_chart(fig, "08_power_profile.png")


def save_chart(fig, filename: str):
    """Save a chart to the output directory."""
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    filepath = os.path.join(OUTPUT_DIR, filename)
    fig.savefig(filepath, dpi=150, bbox_inches='tight',
                facecolor=fig.get_facecolor(), edgecolor='none')
    plt.close(fig)
    print(f"  ✓ Saved: {filename}")


def main():
    print("\n" + "═"*60)
    print("  FoxESS Solar Data Visualizer")
    print("  Generating charts from extracted data")
    print("═"*60)

    # Load data
    print("\n[STEP 1] Loading data...")
    df_report = load_report_data()
    df_history = load_history_data()

    # Generate charts
    print("\n[STEP 2] Generating charts...\n")

    chart_1_daily_generation(df_report)
    chart_2_energy_flow(df_report)
    chart_3_weekly_heatmap(df_report)
    chart_4_cumulative_generation(df_report)
    chart_5_self_sufficiency(df_report)
    chart_6_box_plot_weekly(df_report)
    chart_7_summary_dashboard(df_report)
    chart_8_history_power_profile(df_history)

    # Summary
    print("\n" + "═"*60)
    print("  VISUALIZATION COMPLETE!")
    print("═"*60)
    print(f"  📁 Charts saved to: {OUTPUT_DIR}")
    print(f"  📊 Total charts generated: 8")
    print("═"*60 + "\n")


if __name__ == "__main__":
    main()
